name: Selenium Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Run Selenium test
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        export PATH="$PATH:/usr/lib/chromium-browser/"
        ruby test.rb # Replace with the path to your test script
