name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: actions/setup-ruby@v3
        with:
          ruby-version: '3.2'  # Replace with your desired Ruby version

      - name: Install dependencies
        run: |
          gem install selenium-webdriver headless

      # Install Chrome and ChromeDriver (replace with appropriate actions or scripts)

      - name: Run tests
        run: |
          headless = Headless.new
          headless.start
          ruby test.rb
          headless.destroy
